/*
 * tools/pack.js —— 打两种 zip
 *
 *   node tools/pack.js            扩展包：把 extension/ 打成可上传 AMO 的包
 *   node tools/pack.js --source   源码包：整个项目打包，供 AMO 源码审核用
 *
 * AMO 要求扩展包里的 manifest.json 位于压缩包根目录（不能有外层文件夹），
 * 所以这里自己控制条目路径，不用系统压缩工具（它们的行为随平台变）。
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { zipWrite } = require('./lib');

const ROOT = path.join(__dirname, '..');
const EXT_DIR = path.join(ROOT, 'extension');
const DIST_DIR = path.join(ROOT, 'dist');

// 打包扩展时忽略的杂项
const IGNORE = ['.DS_Store', 'Thumbs.db', '.git', 'node_modules'];
// 打包源码时额外忽略：产物目录和工具自己的配置文件
const SOURCE_IGNORE = IGNORE.concat(['dist', 'reasonix.toml']);

function collect(dir, prefix, ignore) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let files = [];
  entries.forEach(function (entry) {
    if (ignore.indexOf(entry.name) >= 0) return;
    const full = path.join(dir, entry.name);
    const name = prefix ? prefix + '/' + entry.name : entry.name; // zip 里统一用正斜杠
    if (entry.isDirectory()) {
      files = files.concat(collect(full, name, ignore));
    } else if (entry.isFile()) {
      files.push({ name: name, data: fs.readFileSync(full) });
    }
  });
  return files;
}

function readManifest() {
  const manifestPath = path.join(EXT_DIR, 'manifest.json');
  if (!fs.existsSync(manifestPath)) {
    console.error('找不到 extension/manifest.json');
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
}

function report(title, files, outPath, buffer, footer) {
  console.log(title);
  console.log('打包：' + files.length + ' 个文件');
  files
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .forEach(function (file) {
      console.log('  ' + file.name.padEnd(40) + String(file.data.length).padStart(7) + ' B');
    });
  console.log('输出：' + path.relative(ROOT, outPath) + '（' + buffer.length + ' B）');
  if (footer) {
    console.log('');
    console.log(footer);
  }
}

/** 扩展包：只含 extension/ 下的内容 */
function packExtension(manifest) {
  if (!fs.existsSync(EXT_DIR)) {
    console.error('找不到 extension/ 目录');
    process.exit(1);
  }

  const files = collect(EXT_DIR, '', IGNORE);
  if (!files.some((file) => file.name === 'manifest.json')) {
    console.error('manifest.json 不在压缩包根目录');
    process.exit(1);
  }

  fs.mkdirSync(DIST_DIR, { recursive: true });
  const outPath = path.join(DIST_DIR, 'foxhome-' + manifest.version + '.zip');
  const buffer = zipWrite(files);
  fs.writeFileSync(outPath, buffer);

  report(
    '扩展：' + manifest.name + ' ' + manifest.version + '（manifest v' + manifest.manifest_version + '）',
    files,
    outPath,
    buffer,
    '下一步：把上面这个 zip 上传到 https://addons.mozilla.org/developers/addon/submit/\n'
      + '选 “On your own site”（unlisted），提交后即可在开发者后台下载签名好的 .xpi。'
  );
}

/** AMO 源码审核要看的说明，随源码包一起给出 */
function buildNotes(manifest) {
  return [
    '# Source notes — ' + manifest.name + ' ' + manifest.version,
    '',
    'Add-on ID: `' + ((manifest.browser_specific_settings || {}).gecko || {}).id + '`',
    '',
    '## Are build tools used?',
    '',
    'The HTML, CSS and JavaScript that ship in the add-on are **hand-written, unminified,',
    'untranspiled and unbundled**. `extension/manifest.json`, `extension/index.html`,',
    '`extension/assets/*` (the new-tab page), `extension/background.js` and `extension/content.js`',
    'are copied byte-for-byte into the signed package. There is no bundler, no transpiler, no',
    'template engine and no post-processing step.',
    '',
    '## The only generated files',
    '',
    '`extension/icons/icon-16.png` … `icon-128.png` are generated by `tools/make-icons.js`.',
    '',
    'Why: Firefox does not accept SVG as an extension icon, so the icons are rendered pixel',
    'by pixel in plain JavaScript (4x–8x supersampled anti-aliasing) and encoded to PNG by a',
    'small encoder written on top of Node\'s built-in `zlib`. No third-party packages, no',
    'network access, no minification of any kind.',
    '',
    'Reproduce:',
    '',
    '```',
    'node tools/make-icons.js                 # rewrites extension/icons/*.png',
    'node tools/make-icons.js --preview=p.png  # renders a multi-size comparison sheet',
    '```',
    '',
    'The output is deterministic: the same script always produces the same PNG bytes.',
    '',
    '## Repository layout',
    '',
    '| Path | Role |',
    '| --- | --- |',
    '| `extension/` | everything that ships: manifest, scripts, icons, and the new-tab page |',
    '| `extension/index.html`, `extension/assets/` | the start page (hand-written HTML/CSS/JS) |',
    '| `tools/` | icon generator and zip packer — development only, **not** shipped |',
    '| `tests/` | unit tests for the page logic |',
    '',
    '## What the add-on does with data',
    '',
    '- Replaces the new tab page with `extension/index.html` via `chrome_url_overrides.newtab`.',
    '- That page runs with privileged API access, so it calls `browser.history.search()` (the',
    '  `history` permission) directly. The result is rendered locally and never sent anywhere.',
    '- `extension/content.js` only matters when the same page is opened from a `file://` URL;',
    '  it forwards the request and the background script validates `sender.url`, so only',
    '  `.../FoxHome/extension/index.html` can obtain history.',
    '- Nothing is transmitted to any server, nothing is stored by the add-on itself.',
    '',
    '`data_collection_permissions: { required: ["none"] }` in the manifest reflects this.',
    '',
  ].join('\n');
}

/** 源码包：整个项目（供 AMO 源码审核） */
function packSource(manifest) {
  const files = collect(ROOT, '', SOURCE_IGNORE);
  files.push({ name: 'SOURCE-NOTES.md', data: Buffer.from(buildNotes(manifest), 'utf8') });

  const addonFiles = files.filter((file) => file.name.indexOf('extension/') === 0);
  if (!addonFiles.some((file) => file.name === 'extension/manifest.json')) {
    console.error('源码包里没有找到 extension/manifest.json');
    process.exit(1);
  }

  fs.mkdirSync(DIST_DIR, { recursive: true });
  const outPath = path.join(DIST_DIR, 'foxhome-' + manifest.version + '-source.zip');
  const buffer = zipWrite(files);
  fs.writeFileSync(outPath, buffer);

  report(
    '源码：' + manifest.name + ' ' + manifest.version + '（含扩展、图标生成脚本、说明）',
    files,
    outPath,
    buffer,
    '如果 AMO 表里问“是否使用过代码生成/合并/模板等工具”，请选「是」，然后上传这个源码包，\n'
      + '并在说明框里注明：JS 是手写未压缩的，唯一由脚本生成的是图标 PNG（tools/make-icons.js）。\n'
      + '包里的 SOURCE-NOTES.md 已经把这段话写好了，可直接粘贴。'
  );
}

function main() {
  const manifest = readManifest();
  const wantSource = process.argv.slice(2).indexOf('--source') >= 0;
  if (wantSource) packSource(manifest);
  else packExtension(manifest);
}

main();
